# Generated by Django 3.0.1 on 2020-12-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='null', max_length=120),
            preserve_default=False,
        ),
    ]
